# Generated by Django 3.0.1 on 2020-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bastaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/ba')),
            ],
        ),
        migrations.CreateModel(
            name='Bcomstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/bcom')),
            ],
        ),
        migrations.CreateModel(
            name='Biostaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/bio')),
            ],
        ),
        migrations.CreateModel(
            name='Bmsstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/bms')),
            ],
        ),
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Conferences-img', max_length=50)),
                ('conferences', models.ImageField(upload_to='college/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Csstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/cs')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='event-img', max_length=50)),
                ('event', models.ImageField(upload_to='college/event')),
            ],
        ),
        migrations.CreateModel(
            name='Itstaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('joinning_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='college/photo/it')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Library-img', max_length=50)),
                ('library', models.ImageField(upload_to='college/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sport-img', max_length=50)),
                ('sport', models.ImageField(upload_to='college/sport')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
                ('updations_date', models.DateField()),
            ],
        ),
    ]
