# Generated by Django 3.0.1 on 2020-02-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20200224_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone2',
            field=models.IntegerField(),
        ),
    ]
