# Generated by Django 3.0.1 on 2020-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20200225_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Csstaff',
            new_name='Staff',
        ),
        migrations.AlterField(
            model_name='conferences',
            name='conferences',
            field=models.ImageField(upload_to='college/conference'),
        ),
        migrations.AlterField(
            model_name='library',
            name='library',
            field=models.ImageField(upload_to='college/library'),
        ),
    ]
