# Generated by Django 3.0.1 on 2020-03-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20200313_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biostaff',
        ),
    ]
