# Generated by Django 3.0.1 on 2020-03-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_delete_biostaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bastaff',
        ),
        migrations.DeleteModel(
            name='Bcomstaff',
        ),
        migrations.DeleteModel(
            name='Bmsstaff',
        ),
        migrations.DeleteModel(
            name='Itstaff',
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='college/photo/it'),
        ),
    ]
