# Generated by Django 3.0.1 on 2020-03-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_auto_20200313_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='depatment',
            field=models.CharField(default='', max_length=20),
        ),
    ]
