# Generated by Django 3.0.1 on 2020-03-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_staff_depatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='hsc_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sem1_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sem2_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sem3_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sem4_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sem5_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
        migrations.AddField(
            model_name='form',
            name='ssc_result',
            field=models.ImageField(default='', upload_to='college/form_image'),
        ),
    ]
