# Generated by Django 3.0.1 on 2020-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20200313_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='sem5_result',
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='college/staff'),
        ),
    ]
