# Generated by Django 3.0.1 on 2020-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20200314_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='hsc_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(upload_to='college/form/image'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sem1_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sem2_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sem3_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
        migrations.AlterField(
            model_name='form',
            name='sem4_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
        migrations.AlterField(
            model_name='form',
            name='ssc_result',
            field=models.ImageField(default='', upload_to='college/form/result'),
        ),
    ]
