# Generated by Django 2.2.12 on 2020-04-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20200318_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submition_date',
            field=models.DateField(auto_now=True),
        ),
    ]
