# Generated by Django 2.2.12 on 2020-04-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_auto_20200424_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
