# Generated by Django 2.2.12 on 2020-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_delete_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='college/Nss')),
                ('videos', models.FileField(null=True, upload_to='college/videos', verbose_name='')),
            ],
        ),
    ]
