# Generated by Django 2.2.12 on 2020-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_nss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nssimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='college/Nss')),
            ],
        ),
        migrations.DeleteModel(
            name='Nss',
        ),
    ]
