# Generated by Django 2.2.12 on 2020-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_nssimg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nssimg',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
