# Generated by Django 2.2.12 on 2020-05-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_auto_20200523_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nssimg',
        ),
    ]
