# Generated by Django 2.2.12 on 2020-05-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_delete_nssimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nssimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='college/Nss')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
