# Generated by Django 2.2.12 on 2020-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_nssimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nssimg',
            name='date',
        ),
    ]
